tasks:
  - init: |
      cd ./container-alpha
      npm install
    command: |
      npm run "astro dev"
ports:
  - port: 5000
    onOpen: ignore
vscode:
  extensions:
    - svelte.svelte-vscode
    - oouo-diogo-perdigao.docthis
    - cschleiden.vscode-github-actions
    - eamodio.gitlens
    - codeandstuff.package-json-upgrade
    - esbenp.prettier-vscode
    - gencer.html-slim-scss-css-class-completion
    - jerrygoyal.shortcut-menu-bar
    - dotjoshjohnson.xml
    - ms-azuretools.vscode-docker